### the same - see gateway route
GET http://localhost:8082/users-status-check
Authorization: Bearer

###
GET http://localhost:8082/uws/users/status/check

###
GET http://localhost:8082/users-ws/actuator/health

###
POST http://localhost:8082/users-ws/users
Content-Type: application/json
Accept: application/xml

{
  "firstName": "First",
  "lastName": "Second",
  "email": "first.second@gmail.com",
  "password": 12345678
}

###
POST http://localhost:8082/users-ws/users/login
Content-Type: application/json
Accept: application/xml

{
  "email": "first.second@gmail.com",
  "password": 12345678
}

###
GET http://localhost:8082/users-ws/users/status/check
Authorization: Bearer

###
POST http://localhost:8012/actuator/busrefresh

###
GET http://localhost:8012/users-ws/git

###
GET http://localhost:8012/users-ws/native

###
GET http://localhost:8012/api-gateway/native

###
POST http://localhost:8012/encrypt
Content-Type: text/plain

11114ff0-0671-4329-8b72-d120a36b226d

###
POST http://localhost:8012/decrypt
Content-Type: text/plain

6af68290f9b59d8ea6451de1b29cd2ae5c075d71774eda03c294c401a63cf114