### the same - see gateway route
GET http://localhost:8082/users-status-check
Authorization: Bearer test

###
GET http://localhost:8082/uws/users/status/check

###
POST http://localhost:8082/users-ws/users
Content-Type: application/json
Accept: application/xml

{
  "firstName": "First",
  "lastName": "Second",
  "email": "first.second@gmail.com",
  "password": 12345678
}

###
POST http://localhost:8082/users-ws/users/login
Content-Type: application/json
Accept: application/xml

{
  "email": "first.second@gmail.com",
  "password": 12345678
}

###
GET http://localhost:8082/users-ws/users/status/check
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ZjdhNTIyYy1kNTNmLTQ0MDQtODM3OC00N2UxMWE1M2FmNjIiLCJleHAiOjE2MjI2NTkzMzR9.3W1G3sf9Sy8zQsil1KsAESNV9C1uh-3yyOCHKphPB_FmatpN-ouC6E5HcqSZZUx4So9ygBBsHvzfl3FTDkGFvg
